### PR TITLE
wlan_api.go: add support for specifying interface guid and print descriptive errors

### PR DESCRIPTION
**Pull request by saransappa**
This changeset contains the following:
1. Support for specifying interface GUID as an argument along with SSID, username and password
2. Interface GUID is optional. If it is not specified, the PEAP credentials are configured for all interfaces
3. Print SUCCESS and ERROR messages to CLI

### CODE REVIEW

**Comment by saransappa** [comment]
FYI, I did not add the new binary in this PR.

**Comment by tejaskumark** [comment]
@saransappa Can you also please commit binary under misc dir?

**Comment by saransappa** [comment]
@tejaskumark Updated the latest binary and also made the required change in client.py

**Comment by tejaskumark** [comment]
@saransappa Perfect. Thanks for the changes.

**Pull request merged**
